### ISSUE TITLE
Verfmt fallout

### ISSUE THREAD

**Issue by superm1** [fwupd/lvfs-website#426]
Move this into an issue so it's not lost in a closed [Github PR](https://github.com/fwupd/lvfs-website/pull/424).

- [ ] As recently as today I've reproduced failures with dell-dock and the Realtek hubs.
```
No releases found for device: Firmware version formats were different, device was 'pair' and release is 'quad'
```

- [ ] This weekend I reproduced this failure with 8bitdo sf30 pro:
```
No releases found for device: Firmware version formats were different, device was 'pair' and release is 'bcd', Firmware version formats were different, device was 'pair' and release is 'bcd', Firmware version formats were different, device was 'pair' and release is 'bcd'
```

- [x] And someone reported for Thunderbolt this failure (https://github.com/fwupd/fwupd/issues/1551)
```
No releases found for device: Firmware version formats were different, device was 'pair' and release is 'bcd'
```
I tried that specifically myself with a 9380 this morning, but couldn't reproduce it.

**Comment by superm1** [comment]
Thunderbolt is confirmed fixed now.

**Comment by superm1** [comment]
On the Realtek controllers in dell-dock, I did double check the metadata had `LVFS::VersionFormat` set to `pair`, but on LVFS it's indeed overridden to quad in stable channel.

**Comment by hughsie** [comment]
The stable dell dock firmware (https://www.fwupd.org/lvfs/firmware/1915) doesn't actually specify per-component version formats. I'll unbreak things.

**Comment by hughsie** [comment]
I've pushed a change to relax this a bit, and I've just manually refreshed stable, testing and dell-embargo. Can you refresh and re-try please?

**Comment by superm1** [comment]
> The stable dell dock firmware (https://www.fwupd.org/lvfs/firmware/1915) doesn't actually specify per-component version formats. I'll unbreak things.

Oh, the local file I checked was 1.0.8.1, you're right.  The current 1.0.4.1 in stable was before we started putting it in place.

> I've pushed a change to relax this a bit, and I've just manually refreshed stable, testing and dell-embargo. Can you refresh and re-try please?

I'm still seeing it currently.
https://fwupd.org/lvfs/component/2512 and https://fwupd.org/lvfs/component/2513 have 'quad' for VersionFormat.  I guess that needs to be overridden somehow.

**Comment by hughsie** [comment]
> have 'quad' for VersionFormat. I guess that needs to be overridden somehow

I don't think we want to override that. My conclusion is that a per-vendor version format makes a lot less sense when the vendor is actually supporting updates with multiple protocols. E.g. falling back to `quad` makes sense for *UEFI* firmware, but just not anything else. Maybe we should just hardcode that on the LVFS, i.e. only use the vendor-default if the protocol is UEFI...?

**Comment by superm1** [comment]
> Maybe we should just hardcode that on the LVFS, i.e. only use the vendor-default if the protocol is UEFI...?
> 
Yes, I think that is the place that often is the most confusing since everyone seems to interpret a 32 bit integer differently.

So if that's set to only apply on UEFI firmware, the idea being:
* UEFI firmware either needs versionformat set in the CAB or falls back to what's the vendor default
* Non-UEFI firmware either needs set in the CAB or choose a protocol
* Non-UEFI firmware with nothing set in the CAB, no default set in the protocol just gets set empty (earlier FW already on LVFS do nothing - but new firmware uploads need the CAB fixed).

Sound right?

**Comment by superm1** [comment]
And just confirmed everything is working again for the dell-dock devices.
